### **Advanced SQL**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<font color="red">File access required:</font> In Colab this notebook requires first uploading files **Cities.csv**, **Countries.csv**, **Players.csv**, and **Teams.csv** using the *Files* feature in the left toolbar. If running the notebook on a local computer, simply ensure these files are in the same workspace as the notebook.

In [2]:
# Set-up
%load_ext sql
%sql sqlite://
import pandas as pd

In [3]:
# Create database tables from CSV files
with open('Cities.csv') as f: Cities = pd.read_csv(f, index_col=0)
%sql drop table if exists Cities;
%sql --persist Cities
with open('Countries.csv') as f: Countries = pd.read_csv(f, index_col=0)
%sql drop table if exists Countries;
%sql --persist Countries

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.
 * sqlite://

'Persisted countries'

#### Look at sample of Cities and Countries tables

In [4]:
%%sql
select * from Cities limit 5

 * sqlite://
Done.

[('Aalborg', 'Denmark', 57.03, 9.92, 7.52),
 ('Aberdeen', 'United Kingdom', 57.17, -2.08, 8.1),
 ('Abisko', 'Sweden', 63.35, 18.83, 0.2),
 ('Adana', 'Turkey', 36.99, 35.32, 18.67),
 ('Albacete', 'Spain', 39.0, -1.87, 12.62)]

In [5]:
%%sql
select * from Countries limit 5

 * sqlite://
Done.

[('Albania', 2.9, 'no', 'yes'),
 ('Andorra', 0.07, 'no', 'no'),
 ('Austria', 8.57, 'yes', 'no'),
 ('Belarus', 9.48, 'no', 'no'),
 ('Belgium', 11.37, 'yes', 'yes')]

### Duplicates, table variables

*Warm-up: Find all cities in the EU with temperature > 15*

In [6]:
%%sql
select city
from Cities, Countries
where Cities.country = Countries.country
and EU = 'yes' and temperature > 15

 * sqlite://
Done.

[('Algeciras',),
 ('Athens',),
 ('Badajoz',),
 ('Barcelona',),
 ('Bari',),
 ('Cartagena',),
 ('Catania',),
 ('Cosenza',),
 ('Granada',),
 ('Huelva',),
 ('Kalamata',),
 ('Lisbon',),
 ('Marbella',),
 ('Messina',),
 ('Palermo',),
 ('Patras',),
 ('Pescara',),
 ('Rome',),
 ('Trikala',),
 ('Valencia',)]

*Modify previous query to return EU countries that have a city with temperature > 15, remove duplicates*

*Find number of countries that have a city with latitude > 60 (start with country list then fix)*

In [7]:
%%sql
select country
from Cities
where latitude > 60

 * sqlite://
Done.

[('Sweden',),
 ('Norway',),
 ('Norway',),
 ('Finland',),
 ('Sweden',),
 ('Finland',),
 ('Finland',),
 ('Norway',),
 ('Finland',)]

*Modify first query to use table variables*

In [8]:
%%sql
select city
from Cities, Countries
where Cities.country = Countries.country
and EU = 'yes' and temperature > 15

 * sqlite://
Done.

[('Algeciras',),
 ('Athens',),
 ('Badajoz',),
 ('Barcelona',),
 ('Bari',),
 ('Cartagena',),
 ('Catania',),
 ('Cosenza',),
 ('Granada',),
 ('Huelva',),
 ('Kalamata',),
 ('Lisbon',),
 ('Marbella',),
 ('Messina',),
 ('Palermo',),
 ('Patras',),
 ('Pescara',),
 ('Rome',),
 ('Trikala',),
 ('Valencia',)]

*Find all pairs of cities with the same longitude; return the city pairs and their (shared) longitude - notice what's wrong and fix it*

In [9]:
%%sql
select C1.city, C2.city, C1.longitude
from Cities C1, Cities C2
where C1.longitude = C2.longitude

 * sqlite://
Done.

[('Aalborg', 'Aalborg', 9.92),
 ('Aberdeen', 'Aberdeen', -2.08),
 ('Abisko', 'Abisko', 18.83),
 ('Adana', 'Adana', 35.32),
 ('Albacete', 'Albacete', -1.87),
 ('Algeciras', 'Algeciras', -5.47),
 ('Amiens', 'Amiens', 2.3),
 ('Amsterdam', 'Amsterdam', 4.92),
 ('Ancona', 'Ancona', 13.5),
 ('Andorra', 'Andorra', 1.52),
 ('Angers', 'Angers', -0.53),
 ('Ankara', 'Ankara', 32.86),
 ('Antalya', 'Antalya', 30.7),
 ('Arad', 'Arad', 21.32),
 ('Athens', 'Athens', 23.73),
 ('Augsburg', 'Augsburg', 10.9),
 ('Bacau', 'Bacau', 26.92),
 ('Badajoz', 'Badajoz', -6.97),
 ('Baia Mare', 'Baia Mare', 23.58),
 ('Balti', 'Balti', 27.91),
 ('Barcelona', 'Barcelona', 2.18),
 ('Bari', 'Bari', 16.87),
 ('Basel', 'Basel', 7.59),
 ('Batman', 'Batman', 41.14),
 ('Belfast', 'Belfast', -5.96),
 ('Belgrade', 'Belgrade', 20.47),
 ('Bergamo', 'Bergamo', 9.67),
 ('Bergen', 'Bergen', 5.32),
 ('Berlin', 'Berlin', 13.4),
 ('Bialystok', 'Bialystok', 23.17),
 ('Bielefeld', 'Bielefeld', 8.53),
 ('Bila Tserkva', 'Bila Tserkva', 30.13),
 ('Bilbao', 'Bilbao', -2.93),
 ('Birmingham', 'Birmingham', -1.92),
 ('Blackpool', 'Blackpool', -3.05),
 ('Bodo', 'Bodo', 14.4),
 ('Bologna', 'Bologna', 11.34),
 ('Bonn', 'Bonn', 7.08),
 ('Bordeaux', 'Bordeaux', -0.6),
 ('Botosani', 'Botosani', 26.66),
 ('Bournemouth', 'Bournemouth', -1.9),
 ('Bradford', 'Bradford', -1.75),
 ('Braga', 'Braga', -8.42),
 ('Braila', 'Braila', 27.97),
 ('Bratislava', 'Bratislava', 17.12),
 ('Bremen', 'Bremen', 8.8),
 ('Brest', 'Brest', -4.5),
 ('Brest', 'Brest', 23.7),
 ('Brno', 'Brno', 16.61),
 ('Brugge', 'Brugge', 3.23),
 ('Bucharest', 'Bucharest', 26.1),
 ('Budapest', 'Budapest', 19.08),
 ('Burgas', 'Burgas', 27.47),
 ('Burgos', 'Burgos', -3.68),
 ('Burgos', 'Madrid', -3.68),
 ('Bursa', 'Bursa', 29.07),
 ('Bydgoszcz', 'Bydgoszcz', 18.01),
 ('Bytom', 'Bytom', 18.91),
 ('Caen', 'Caen', -0.35),
 ('Cambridge', 'Cambridge', 0.12),
 ('Cartagena', 'Cartagena', -0.98),
 ('Catania', 'Catania', 15.08),
 ('Chemnitz', 'Chemnitz', 12.92),
 ('Cherkasy', 'Cherkasy', 32.07),
 ('Chernihiv', 'Chernihiv', 31.3),
 ('Chernivtsi', 'Chernivtsi', 25.92),
 ('Chisinau', 'Chisinau', 28.86),
 ('Constanta', 'Constanta', 28.61),
 ('Cork', 'Cork', -8.5),
 ('Cosenza', 'Cosenza', 16.29),
 ('Craiova', 'Craiova', 23.83),
 ('Craiova', 'Hrodna', 23.83),
 ('Daugavpils', 'Daugavpils', 26.51),
 ('Debrecen', 'Debrecen', 21.63),
 ('Denizli', 'Denizli', 29.08),
 ('Dijon', 'Dijon', 5.03),
 ('Dublin', 'Dublin', -6.25),
 ('Dundee', 'Dundee', -3.0),
 ('Edinburgh', 'Edinburgh', -3.22),
 ('Edirne', 'Edirne', 26.57),
 ('Elbasan', 'Elbasan', 20.08),
 ('Elblag', 'Elblag', 19.4),
 ('Erfurt', 'Erfurt', 11.03),
 ('Erzincan', 'Erzincan', 39.49),
 ('Erzurum', 'Erzurum', 41.29),
 ('Eskisehir', 'Eskisehir', 30.53),
 ('Exeter', 'Exeter', -3.53),
 ('Foggia', 'Foggia', 15.56),
 ('Frankfurt', 'Frankfurt', 8.68),
 ('Freiburg', 'Freiburg', 7.87),
 ('Galway', 'Galway', -9.05),
 ('Gaziantep', 'Gaziantep', 37.38),
 ('Geneva', 'Geneva', 6.14),
 ('Genoa', 'Genoa', 8.93),
 ('Glasgow', 'Glasgow', -4.25),
 ('Göteborg', 'Göteborg', 12.0),
 ('Granada', 'Granada', -3.59),
 ('Graz', 'Graz', 15.41),
 ('Grenoble', 'Grenoble', 5.72),
 ('Groningen', 'Groningen', 6.58),
 ('Gyor', 'Gyor', 17.63),
 ('Heidelberg', 'Heidelberg', 8.7),
 ('Helsinki', 'Helsinki', 24.93),
 ('Horlivka', 'Horlivka', 38.05),
 ('Hrodna', 'Craiova', 23.83),
 ('Hrodna', 'Hrodna', 23.83),
 ('Huelva', 'Huelva', -6.93),
 ('Ingolstadt', 'Ingolstadt', 11.45),
 ('Innsbruck', 'Innsbruck', 11.41),
 ('Inverness', 'Inverness', -4.23),
 ('Istanbul', 'Istanbul', 29.01),
 ('Kalamata', 'Kalamata', 22.11),
 ('Karaman', 'Karaman', 33.22),
 ('Karlsruhe', 'Karlsruhe', 8.4),
 ('Kaunas', 'Kaunas', 23.88),
 ('Kayseri', 'Kayseri', 35.49),
 ('Kherson', 'Kherson', 32.6),
 ('Kielce', 'Kielce', 20.66),
 ('Kiev', 'Kiev', 30.52),
 ('Kiruna', 'Kiruna', 20.22),
 ('Klaipeda', 'Klaipeda', 21.12),
 ('Kosice', 'Kosice', 21.25),
 ('Koszalin', 'Koszalin', 16.18),
 ('Kremenchuk', 'Kremenchuk', 33.43),
 ('Kryvyy Rih', 'Kryvyy Rih', 33.34),
 ('Le Mans', 'Le Mans', 0.1),
 ('Lille', 'Lille', 3.08),
 ('Limoges', 'Limoges', 1.25),
 ('Linz', 'Linz', 14.29),
 ('Lisbon', 'Lisbon', -9.14),
 ('Ljubljana', 'Ljubljana', 14.51),
 ('Lvov', 'Lvov', 24.03),
 ('Maastricht', 'Maastricht', 5.68),
 ('Maastricht', 'Stavanger', 5.68),
 ('Madrid', 'Burgos', -3.68),
 ('Madrid', 'Madrid', -3.68),
 ('Magdeburg', 'Magdeburg', 11.62),
 ('Makiyivka', 'Makiyivka', 37.97),
 ('Malatya', 'Malatya', 38.3),
 ('Malmö', 'Malmö', 13.03),
 ('Manisa', 'Manisa', 27.44),
 ('Marbella', 'Marbella', -4.88),
 ('Marseille', 'Marseille', 5.38),
 ('Mazyr', 'Mazyr', 29.27),
 ('Messina', 'Messina', 15.55),
 ('Metz', 'Metz', 6.18),
 ('Milan', 'Milan', 9.21),
 ('Minsk', 'Minsk', 27.57),
 ('Montpellier', 'Montpellier', 3.87),
 ('Mulhouse', 'Mulhouse', 7.35),
 ('Murcia', 'Murcia', -1.13),
 ('Nice', 'Nice', 7.27),
 ('Nis', 'Nis', 21.9),
 ('Novi Sad', 'Novi Sad', 19.85),
 ('Odense', 'Odense', 10.38),
 ('Ordu', 'Ordu', 37.87),
 ('Orsha', 'Orsha', 30.42),
 ('Oslo', 'Oslo', 10.75),
 ('Ostrava', 'Ostrava', 18.25),
 ('Oulu', 'Oulu', 25.47),
 ('Oviedo', 'Oviedo', -5.83),
 ('Palermo', 'Palermo', 13.35),
 ('Patras', 'Patras', 21.73),
 ('Perpignan', 'Perpignan', 2.9),
 ('Perugia', 'Perugia', 12.39),
 ('Pescara', 'Pescara', 14.22),
 ('Pinsk', 'Pinsk', 26.09),
 ('Pleven', 'Pleven', 24.61),
 ('Plovdiv', 'Plovdiv', 24.75),
 ('Podgorica', 'Podgorica', 19.27),
 ('Poznan', 'Poznan', 16.9),
 ('Prague', 'Prague', 14.47),
 ('Reims', 'Reims', 4.03),
 ('Riga', 'Riga', 24.1),
 ('Rijeka', 'Rijeka', 14.45),
 ('Rivne', 'Rivne', 26.25),
 ('Rome', 'Rome', 12.48),
 ('Rostock', 'Rostock', 12.15),
 ('Ruse', 'Ruse', 25.97),
 ('Salamanca', 'Salamanca', -5.67),
 ('Salzburg', 'Salzburg', 13.04),
 ('Samsun', 'Samsun', 36.34),
 ('Santander', 'Santander', -3.8),
 ('Sarajevo', 'Sarajevo', 13.38),
 ('Sibiu', 'Sibiu', 24.14),
 ('Siirt', 'Siirt', 41.93),
 ('Sivas', 'Sivas', 37.03),
 ('Skopje', 'Skopje', 21.43),
 ('Split', 'Split', 16.47),
 ('Stara Zagora', 'Stara Zagora', 25.62),
 ('Stavanger', 'Maastricht', 5.68),
 ('Stavanger', 'Stavanger', 5.68),
 ('Stockholm', 'Stockholm', 18.1),
 ('Sumy', 'Sumy', 34.78),
 ('Swansea', 'Swansea', -3.95),
 ('Szeged', 'Szeged', 20.15),
 ('Tallinn', 'Tallinn', 24.73),
 ('Tampere', 'Tampere', 23.75),
 ('Tarsus', 'Tarsus', 34.88),
 ('Tartu', 'Tartu', 26.71),
 ('Tekirdag', 'Tekirdag', 27.51),
 ('Toulouse', 'Toulouse', 1.45),
 ('Trabzon', 'Trabzon', 39.72),
 ('Trieste', 'Trieste', 13.8),
 ('Trikala', 'Trikala', 21.77),
 ('Trondheim', 'Trondheim', 10.42),
 ('Turku', 'Turku', 22.25),
 ('Uppsala', 'Uppsala', 17.64),
 ('Valencia', 'Valencia', -0.4),
 ('Vienna', 'Vienna', 16.37),
 ('Vigo', 'Vigo', -8.73),
 ('Vilnius', 'Vilnius', 25.32),
 ('Warsaw', 'Warsaw', 21.0),
 ('Wroclaw', 'Wroclaw', 17.03),
 ('Yevpatoriya', 'Yevpatoriya', 33.36),
 ('Zaragoza', 'Zaragoza', -0.89),
 ('Zhytomyr', 'Zhytomyr', 28.66),
 ('Zonguldak', 'Zonguldak', 31.78),
 ('Zurich', 'Zurich', 8.56)]

*Find all pairs of cities that are near each other, i.e., longitude and latitude are both less than 0.5 apart; return city pairs*

In [10]:
%%sql
select C1.city, C2.city
from Cities C1, Cities C2
where abs(C1.longitude - C2.longitude) < .5
and abs(C1.latitude - C2.latitude) < .5
and C1.city < C2.city

 * sqlite://
Done.

[('Adana', 'Tarsus'),
 ('Ancona', 'Sarajevo'),
 ('Basel', 'Freiburg'),
 ('Basel', 'Mulhouse'),
 ('Bergamo', 'Milan'),
 ('Cartagena', 'Murcia'),
 ('Heidelberg', 'Karlsruhe'),
 ('Horlivka', 'Makiyivka')]

### <font color = 'green'>**Your Turn**</font>

*Find all pairs of cities with the same temperature. Return the city pairs along with their shared temperature. What do you think about the data after seeing the answer?*

In [65]:
%%sql
select C1.city, C2.city, C1.temperature
from Cities C1, Cities C2
where C1.temperature = C2.temperature

 * sqlite://
Done.

[('Aalborg', 'Aalborg', 9.099200000000002),
 ('Aberdeen', 'Aberdeen', 9.801),
 ('Abisko', 'Abisko', 0.24200000000000005),
 ('Albacete', 'Albacete', 15.2702),
 ('Algeciras', 'Algeciras', 21.029800000000005),
 ('Amiens', 'Amiens', 12.305700000000002),
 ('Amsterdam', 'Amsterdam', 10.8053),
 ('Ancona', 'Ancona', 16.3592),
 ('Andorra', 'Andorra', 10.56),
 ('Angers', 'Angers', 13.285800000000002),
 ('Arad', 'Arad', 11.277200000000002),
 ('Athens', 'Athens', 21.066100000000006),
 ('Augsburg', 'Augsburg', 5.493400000000001),
 ('Bacau', 'Bacau', 9.087100000000001),
 ('Badajoz', 'Badajoz', 18.8881),
 ('Baia Mare', 'Baia Mare', 10.732700000000001),
 ('Balti', 'Balti', 9.053),
 ('Barcelona', 'Barcelona', 19.0938),
 ('Bari', 'Bari', 18.331500000000005),
 ('Basel', 'Basel', 7.348),
 ('Basel', 'Zurich', 7.348),
 ('Belfast', 'Belfast', 10.260800000000001),
 ('Belgrade', 'Belgrade', 10.835),
 ('Bergamo', 'Bergamo', 11.035200000000001),
 ('Bergen', 'Bergen', 2.1175000000000006),
 ('Berlin', 'Berlin', 10.551200000000003),
 ('Bialystok', 'Bialystok', 7.344700000000001),
 ('Bielefeld', 'Bielefeld', 10.623800000000001),
 ('Bila Tserkva', 'Bila Tserkva', 8.445800000000002),
 ('Bilbao', 'Bilbao', 13.806100000000002),
 ('Birmingham', 'Birmingham', 10.660100000000002),
 ('Blackpool', 'Blackpool', 11.071500000000002),
 ('Bodo', 'Bodo', 5.445),
 ('Bologna', 'Bologna', 14.144900000000002),
 ('Bonn', 'Bonn', 10.442300000000003),
 ('Bonn', 'Maastricht', 10.442300000000003),
 ('Bordeaux', 'Bordeaux', 14.362700000000002),
 ('Botosani', 'Botosani', 9.958300000000001),
 ('Bournemouth', 'Bournemouth', 12.063700000000004),
 ('Bradford', 'Bradford', 10.151900000000001),
 ('Braga', 'Braga', 16.238200000000003),
 ('Braila', 'Braila', 11.833800000000002),
 ('Bratislava', 'Bratislava', 10.615000000000002),
 ('Bratislava', 'Gyor', 10.615000000000002),
 ('Bremen', 'Bremen', 9.849400000000001),
 ('Brest', 'Brest', 13.334200000000001),
 ('Brest', 'Brest', 7.403000000000001),
 ('Brno', 'Brno', 8.646),
 ('Brno', 'Vienna', 8.646),
 ('Brugge', 'Brugge', 11.676500000000003),
 ('Brugge', 'Lille', 11.676500000000003),
 ('Bucharest', 'Bucharest', 12.813900000000002),
 ('Bucharest', 'Le Mans', 12.813900000000002),
 ('Bucharest', 'Ruse', 12.813900000000002),
 ('Budapest', 'Budapest', 10.505),
 ('Burgas', 'Burgas', 14.435300000000002),
 ('Burgos', 'Burgos', 12.644500000000003),
 ('Bydgoszcz', 'Bydgoszcz', 8.6394),
 ('Bytom', 'Bytom', 9.268600000000001),
 ('Caen', 'Caen', 12.051600000000002),
 ('Cambridge', 'Cambridge', 11.192500000000003),
 ('Cartagena', 'Cartagena', 20.957200000000004),
 ('Catania', 'Catania', 18.198400000000003),
 ('Chemnitz', 'Chemnitz', 9.740500000000003),
 ('Cherkasy', 'Cherkasy', 8.699900000000001),
 ('Chernihiv', 'Chernihiv', 7.163200000000001),
 ('Chernivtsi', 'Chernivtsi', 8.5426),
 ('Chisinau', 'Chisinau', 9.46),
 ('Constanta', 'Constanta', 13.600400000000002),
 ('Cork', 'Cork', 11.386100000000003),
 ('Cosenza', 'Cosenza', 20.086000000000002),
 ('Craiova', 'Craiova', 12.7171),
 ('Craiova', 'Pleven', 12.7171),
 ('Daugavpils', 'Daugavpils', 6.5098),
 ('Daugavpils', 'Vilnius', 6.5098),
 ('Debrecen', 'Debrecen', 9.757),
 ('Dijon', 'Dijon', 10.514900000000003),
 ('Dublin', 'Dublin', 10.272900000000002),
 ('Dundee', 'Dundee', 7.7440000000000015),
 ('Edinburgh', 'Edinburgh', 8.990300000000001),
 ('Edinburgh', 'Kremenchuk', 8.990300000000001),
 ('Elbasan', 'Elbasan', 18.367800000000003),
 ('Elblag', 'Elblag', 8.0828),
 ('Elblag', 'Freiburg', 8.0828),
 ('Elblag', 'Mulhouse', 8.0828),
 ('Erfurt', 'Erfurt', 8.954),
 ('Exeter', 'Exeter', 12.269400000000003),
 ('Foggia', 'Foggia', 16.7343),
 ('Frankfurt', 'Frankfurt', 9.655800000000001),
 ('Freiburg', 'Elblag', 8.0828),
 ('Freiburg', 'Freiburg', 8.0828),
 ('Freiburg', 'Mulhouse', 8.0828),
 ('Galway', 'Galway', 12.100000000000001),
 ('Geneva', 'Geneva', 9.240000000000002),
 ('Genoa', 'Genoa', 15.6574),
 ('Glasgow', 'Glasgow', 10.406000000000002),
 ('Göteborg', 'Göteborg', 6.969600000000001),
 ('Granada', 'Granada', 19.759300000000003),
 ('Graz', 'Graz', 7.601000000000001),
 ('Grenoble', 'Grenoble', 10.164000000000003),
 ('Groningen', 'Groningen', 10.539100000000003),
 ('Gyor', 'Bratislava', 10.615000000000002),
 ('Gyor', 'Gyor', 10.615000000000002),
 ('Heidelberg', 'Heidelberg', 10.248700000000003),
 ('Helsinki', 'Helsinki', 5.069900000000001),
 ('Horlivka', 'Horlivka', 8.615200000000002),
 ('Hrodna', 'Hrodna', 6.6770000000000005),
 ('Huelva', 'Huelva', 20.678900000000006),
 ('Ingolstadt', 'Ingolstadt', 9.159700000000003),
 ('Innsbruck', 'Innsbruck', 4.994000000000001),
 ('Inverness', 'Inverness', 9.680000000000001),
 ('Kalamata', 'Kalamata', 20.933000000000003),
 ('Karlsruhe', 'Karlsruhe', 10.744800000000003),
 ('Karlsruhe', 'Metz', 10.744800000000003),
 ('Kaunas', 'Kaunas', 7.320500000000001),
 ('Kherson', 'Kherson', 10.454400000000001),
 ('Kielce', 'Kielce', 8.820900000000002),
 ('Kiev', 'Kiev', 8.324800000000002),
 ('Kiruna', 'Kiruna', -2.662000000000001),
 ('Klaipeda', 'Klaipeda', 8.470000000000002),
 ('Kosice', 'Kosice', 8.041),
 ('Koszalin', 'Koszalin', 9.353300000000003),
 ('Koszalin', 'Odense', 9.353300000000003),
 ('Kremenchuk', 'Edinburgh', 8.990300000000001),
 ('Kremenchuk', 'Kremenchuk', 8.990300000000001),
 ('Kryvyy Rih', 'Kryvyy Rih', 10.4181),
 ('Le Mans', 'Bucharest', 12.813900000000002),
 ('Le Mans', 'Le Mans', 12.813900000000002),
 ('Le Mans', 'Ruse', 12.813900000000002),
 ('Lille', 'Brugge', 11.676500000000003),
 ('Lille', 'Lille', 11.676500000000003),
 ('Limoges', 'Limoges', 12.487200000000003),
 ('Linz', 'Linz', 7.469),
 ('Lisbon', 'Lisbon', 18.7792),
 ('Ljubljana', 'Ljubljana', 11.216700000000001),
 ('Ljubljana', 'Rijeka', 11.216700000000001),
 ('Lvov', 'Lvov', 8.518400000000002),
 ('Maastricht', 'Bonn', 10.442300000000003),
 ('Maastricht', 'Maastricht', 10.442300000000003),
 ('Madrid', 'Madrid', 13.539900000000003),
 ('Magdeburg', 'Magdeburg', 9.994600000000002),
 ('Makiyivka', 'Makiyivka', 10.527000000000001),
 ('Malmö', 'Malmö', 8.8693),
 ('Marbella', 'Marbella', 20.799900000000004),
 ('Marseille', 'Marseille', 18.1258),
 ('Mazyr', 'Mazyr', 6.875000000000001),
 ('Messina', 'Messina', 20.0134),
 ('Metz', 'Karlsruhe', 10.744800000000003),
 ('Metz', 'Metz', 10.744800000000003),
 ('Milan', 'Milan', 8.046500000000002),
 ('Minsk', 'Minsk', 5.808000000000001),
 ('Montpellier', 'Montpellier', 13.443100000000001),
 ('Mulhouse', 'Elblag', 8.0828),
 ('Mulhouse', 'Freiburg', 8.0828),
 ('Mulhouse', 'Mulhouse', 8.0828),
 ('Murcia', 'Murcia', 18.150000000000002),
 ('Nice', 'Nice', 10.672200000000002),
 ('Nis', 'Nis', 10.296),
 ('Nis', 'Skopje', 10.296),
 ('Novi Sad', 'Novi Sad', 11.374),
 ('Novi Sad', 'Szeged', 11.374),
 ('Odense', 'Koszalin', 9.353300000000003),
 ('Odense', 'Odense', 9.353300000000003),
 ('Orsha', 'Orsha', 5.423),
 ('Oslo', 'Oslo', 2.8072000000000004),
 ('Ostrava', 'Ostrava', 8.426),
 ('Oulu', 'Oulu', 1.7545000000000002),
 ('Oviedo', 'Oviedo', 13.1285),
 ('Palermo', 'Palermo', 21.659000000000002),
 ('Patras', 'Patras', 20.449),
 ('Perpignan', 'Perpignan', 13.249500000000001),
 ('Perugia', 'Perugia', 14.157000000000002),
 ('Pescara', 'Pescara', 18.3073),
 ('Pinsk', 'Pinsk', 7.062),
 ('Pleven', 'Craiova', 12.7171),
 ('Pleven', 'Pleven', 12.7171),
 ('Plovdiv', 'Plovdiv', 10.0067),
 ('Podgorica', 'Podgorica', 12.087900000000001),
 ('Poznan', 'Poznan', 10.055100000000003),
 ('Prague', 'Prague', 8.855000000000002),
 ('Reims', 'Reims', 11.374000000000002),
 ('Riga', 'Riga', 6.243600000000002),
 ('Rijeka', 'Ljubljana', 11.216700000000001),
 ('Rijeka', 'Rijeka', 11.216700000000001),
 ('Rivne', 'Rivne', 8.1796),
 ('Rome', 'Rome', 18.271),
 ('Rostock', 'Rostock', 9.764700000000001),
 ('Ruse', 'Bucharest', 12.813900000000002),
 ('Ruse', 'Le Mans', 12.813900000000002),
 ('Ruse', 'Ruse', 12.813900000000002),
 ('Salamanca', 'Salamanca', 14.072300000000002),
 ('Salzburg', 'Salzburg', 5.082000000000001),
 ('Santander', 'Santander', 16.214000000000002),
 ('Sarajevo', 'Sarajevo', 11.616000000000001),
 ('Sibiu', 'Sibiu', 8.433700000000002),
 ('Skopje', 'Nis', 10.296),
 ('Skopje', 'Skopje', 10.296),
 ('Split', 'Split', 15.076600000000003),
 ('Stara Zagora', 'Stara Zagora', 13.189000000000004),
 ('Stavanger', 'Stavanger', 6.691300000000002),
 ('Stockholm', 'Stockholm', 7.574600000000001),
 ('Sumy', 'Sumy', 7.5988000000000016),
 ('Swansea', 'Swansea', 11.773300000000003),
 ('Szeged', 'Novi Sad', 11.374),
 ('Szeged', 'Szeged', 11.374),
 ('Tallinn', 'Tallinn', 5.832200000000001),
 ('Tampere', 'Tampere', 4.3439000000000005),
 ('Tartu', 'Tartu', 5.275600000000002),
 ('Toulouse', 'Toulouse', 12.402500000000002),
 ('Trieste', 'Trieste', 13.564100000000003),
 ('Trikala', 'Trikala', 19.360000000000003),
 ('Trondheim', 'Trondheim', 5.481300000000001),
 ('Turku', 'Turku', 5.711200000000001),
 ('Uppsala', 'Uppsala', 5.045700000000001),
 ('Valencia', 'Valencia', 19.3842),
 ('Vienna', 'Brno', 8.646),
 ('Vienna', 'Vienna', 8.646),
 ('Vigo', 'Vigo', 15.548500000000002),
 ('Vilnius', 'Daugavpils', 6.5098),
 ('Vilnius', 'Vilnius', 6.5098),
 ('Warsaw', 'Warsaw', 8.712000000000002),
 ('Wroclaw', 'Wroclaw', 8.6757),
 ('Yevpatoriya', 'Yevpatoriya', 12.124200000000002),
 ('Zaragoza', 'Zaragoza', 17.1457),
 ('Zhytomyr', 'Zhytomyr', 8.070700000000002),
 ('Zurich', 'Basel', 7.348),
 ('Zurich', 'Zurich', 7.348)]

### Subqueries in Where clause

*Find all countries in the Countries table with no city in the Cities table*

In [12]:
%%sql
select country
from Countries
where not exists (select * from Cities
                  where Cities.country = Countries.country)

 * sqlite://
Done.

[('Cyprus',), ('Iceland',), ('Kosovo',), ('Liechtenstein',), ('Luxembourg',)]

*Find countries in the EU that have a city with temperature > 15*

In [13]:
%%sql
select country
from Countries
where EU = 'yes'
and exists (select * from Cities
            where Cities.country = Countries.country
            and temperature > 15)

 * sqlite://
Done.

[('Greece',), ('Italy',), ('Portugal',), ('Spain',)]

*Find number of countries that have a city with latitude > 60 (start with country list)*

In [14]:
%%sql
select country
from Countries
where exists (select * from Cities
              where Cities.country = Countries.country
              and latitude > 60)

 * sqlite://
Done.

[('Finland',), ('Norway',), ('Sweden',)]

*Find the westernmost city; return the city and longitude*

In [15]:
%%sql
select city, longitude
from Cities C1
where not exists (select * from Cities C2
                  where C2.longitude < C1.longitude)

 * sqlite://
Done.

[('Lisbon', -9.14)]

*Add easternmost to previous query*

*Westernmost city query using = and min*

In [16]:
%%sql
select city, longitude
from Cities
where longitude = (select min(longitude) from Cities)

 * sqlite://
Done.

[('Lisbon', -9.14)]

*Find all cities whose temperature is more than 50% higher than the average; return the city, country, and temperature, ordered by descending temperature*

In [17]:
%%sql
select city, country, temperature
from Cities
where temperature > (select avg(temperature) * 1.5 from Cities)
order by temperature desc

 * sqlite://
Done.

[('Adana', 'Turkey', 18.67),
 ('Palermo', 'Italy', 17.9),
 ('Athens', 'Greece', 17.41),
 ('Algeciras', 'Spain', 17.38),
 ('Cartagena', 'Spain', 17.32),
 ('Kalamata', 'Greece', 17.3),
 ('Marbella', 'Spain', 17.19),
 ('Huelva', 'Spain', 17.09),
 ('Patras', 'Greece', 16.9),
 ('Cosenza', 'Italy', 16.6),
 ('Messina', 'Italy', 16.54),
 ('Granada', 'Spain', 16.33),
 ('Valencia', 'Spain', 16.02),
 ('Trikala', 'Greece', 16.0),
 ('Barcelona', 'Spain', 15.78),
 ('Badajoz', 'Spain', 15.61),
 ('Lisbon', 'Portugal', 15.52),
 ('Elbasan', 'Albania', 15.18),
 ('Bari', 'Italy', 15.15),
 ('Pescara', 'Italy', 15.13),
 ('Manisa', 'Turkey', 15.1),
 ('Rome', 'Italy', 15.1),
 ('Catania', 'Italy', 15.04),
 ('Denizli', 'Turkey', 15.02),
 ('Murcia', 'Spain', 15.0),
 ('Marseille', 'France', 14.98)]

*Number of cities in the EU*

In [18]:
%%sql
select count()
from Cities
where country in (select country from Countries where EU = 'yes')

 * sqlite://
Done.

[(150,)]

*Modify previous query to use "not in"*

*Same query using join instead of subquery*

In [19]:
%%sql
select count()
from Cities, Countries
where Cities.country = Countries.country
and EU = 'yes'

 * sqlite://
Done.

[(150,)]

*Number of countries with no coastline and a city with longitude < 20*

In [20]:
%%sql
select count()
from Countries
where coastline = 'no'
and exists (select * from Cities where country = Countries.country
            and longitude < 20)

 * sqlite://
Done.

[(7,)]

*Same query using join instead of subquery (see what's wrong and fix it)*

In [21]:
%%sql
select count()
from Countries, Cities
where Countries.country = Cities.country
and coastline = 'no' and longitude < 20

 * sqlite://
Done.

[(16,)]

*Find countries in Countries table with no city in Cities table using join instead of subquery (subquery version repeated first)*

In [22]:
%%sql
select country
from Countries
where not exists (select * from Cities
                  where Cities.country = Countries.country)

 * sqlite://
Done.

[('Cyprus',), ('Iceland',), ('Kosovo',), ('Liechtenstein',), ('Luxembourg',)]

### <font color = 'green'>**Your Turn**</font>

*Find all cities in a country whose population is < 2; return the city and country. First write the query without a subquery.*

In [67]:
%%sql
select city, country
from Cities
where country in (select country from Countries where population < 2)

 * sqlite://
Done.

[('Andorra', 'Andorra'),
 ('Daugavpils', 'Latvia'),
 ('Podgorica', 'Montenegro'),
 ('Riga', 'Latvia'),
 ('Tallinn', 'Estonia'),
 ('Tartu', 'Estonia')]

*Now write the same query using a subquery instead of a join.*

In [68]:
%%sql
select city, country
from Cities
where country in (select country from Countries where population < 2)

 * sqlite://
Done.

[('Andorra', 'Andorra'),
 ('Daugavpils', 'Latvia'),
 ('Podgorica', 'Montenegro'),
 ('Riga', 'Latvia'),
 ('Tallinn', 'Estonia'),
 ('Tartu', 'Estonia')]

*Find all countries with no city having a temperature > 6*

In [69]:
%%sql
select country
from Countries
where not exists (select * from Cities
                  where Cities.country = Countries.country
                  and temperature > 6)

 * sqlite://
Done.

[('Cyprus',),
 ('Estonia',),
 ('Finland',),
 ('Iceland',),
 ('Kosovo',),
 ('Liechtenstein',),
 ('Luxembourg',),
 ('Turkey',)]

*Now try to write the same query without a subquery; can you?*

In [101]:
%%sql
select Countries.country from Cities join Countries
where Cities.country = Countries.country
and temperature < 6
group by Cities.country

 * sqlite://
Done.

[('Austria',),
 ('Belarus',),
 ('Estonia',),
 ('Finland',),
 ('Germany',),
 ('Norway',),
 ('Sweden',)]

### Aggregation with Having clause

*Find all countries with average city temperature > 10; return country and average temperature*

In [28]:
%%sql
select country, avg(temperature)
from Cities
group by country
having avg(temperature) > 10

 * sqlite://
Done.

[('Albania', 15.18),
 ('Bulgaria', 10.44),
 ('Croatia', 10.865),
 ('France', 10.151111111111112),
 ('Greece', 16.9025),
 ('Italy', 13.474666666666668),
 ('Portugal', 14.469999999999999),
 ('Spain', 14.238333333333332),
 ('Turkey', 11.726666666666665)]

*Find all countries with more than 5 cities above latitude 50*

In [29]:
%%sql
select country
from Cities
where latitude > 50
group by country
having count() > 5

 * sqlite://
Done.

[('Belarus',), ('Germany',), ('Poland',), ('Sweden',), ('United Kingdom',)]

*Same query without Having clause*

In [30]:
%%sql
select distinct country
from Cities C1
where 5 < (select count() from Cities C2
           where C1.country=C2.country
           and latitude > 50)

 * sqlite://
Done.

[('United Kingdom',), ('Sweden',), ('Germany',), ('Poland',), ('Belarus',)]

*Which combinations of EU versus non-EU and coastline versus no-coastline have a minimum population greater than 0.5?*

In [31]:
%%sql
select EU, coastline, min(population)
from Countries
group by EU, coastline
having min(population) > 0.5

 * sqlite://
Done.

[('yes', 'no', 0.58), ('yes', 'yes', 1.18)]

*Find all countries with average city temperature more than 50% higher than the overall average; return country and average temperature*

In [32]:
%%sql
select country, avg(temperature)
from Cities
group by country
having avg(temperature) > (select 1.5 * avg(temperature) from Cities)

 * sqlite://
Done.

[('Albania', 15.18), ('Greece', 16.9025), ('Portugal', 14.469999999999999)]

### <font color = 'green'>**Your Turn**</font>

*Find all countries whose average city longitude is lower than the overall average longitude, and whose average city latitude is higher than the overall average latitude. Return the countries. Note: Yes, you can use "and" in Having clauses!*

In [33]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

### Subqueries in From and Select clauses

*Find all countries with both cold and warm cities -- at least one city with temperature < 9 and one city with temperature > 14*

In [34]:
%%sql
select distinct C1.country
from Cities C1, Cities C2
where C1.country = C2.country
and C1.temperature < 9 and C2.temperature > 14

 * sqlite://
Done.

[('France',), ('Turkey',), ('Italy',)]

*Modify query to also return count of cold and warm cities (then show without column renaming)*

In [35]:
# (select count() from Cities where country = C1.country and temperature < 9) as numcold,
# (select count() from Cities where country = C1.country and temperature > 14) as numwarm

*Same query using subquery in From clause instead of Select clause*

In [36]:
%%sql
select Cold.country, numcold, numwarm
from (select country, count() as numcold from Cities
      where temperature < 9 group by country) Cold,
     (select country, count() as numwarm from Cities
      where temperature > 14 group by country) Warm
where Cold.country = Warm.country

 * sqlite://
Done.

[('France', 5, 1), ('Italy', 1, 7), ('Turkey', 4, 5)]

### Data modification

*Increase all city temperatures by 10%*

In [37]:
%%sql
update Cities
set temperature = 1.1 * temperature

 * sqlite://
213 rows affected.

[]

In [38]:
%%sql
select avg(temperature) from Cities

 * sqlite://
Done.

[(10.447624413145537,)]

*Increase temperatures another 10% for cities in countries with coastline*

In [39]:
%%sql
update Cities
set temperature = 1.1 * temperature
where country in (select country from Countries
                  where coastline = 'yes')

 * sqlite://
183 rows affected.

[]

*Delete all cities in Turkey*

In [40]:
%%sql
delete from Cities
where country = 'Turkey'

 * sqlite://
24 rows affected.

[]

*Create a new table NonEU containing list of cities (with country) not in the EU*

In [41]:
%%sql
drop table if exists NonEU;
create table NonEU(city, country);
insert into NonEU
  select city, country from cities
  where country in (select country from Countries
                    where EU = 'no');
select * from NonEU

 * sqlite://
Done.
Done.
39 rows affected.
Done.

[('Andorra', 'Andorra'),
 ('Balti', 'Moldova'),
 ('Basel', 'Switzerland'),
 ('Belgrade', 'Serbia'),
 ('Bergen', 'Norway'),
 ('Bila Tserkva', 'Ukraine'),
 ('Bodo', 'Norway'),
 ('Brest', 'Belarus'),
 ('Cherkasy', 'Ukraine'),
 ('Chernihiv', 'Ukraine'),
 ('Chernivtsi', 'Ukraine'),
 ('Chisinau', 'Moldova'),
 ('Elbasan', 'Albania'),
 ('Geneva', 'Switzerland'),
 ('Horlivka', 'Ukraine'),
 ('Hrodna', 'Belarus'),
 ('Kherson', 'Ukraine'),
 ('Kiev', 'Ukraine'),
 ('Kremenchuk', 'Ukraine'),
 ('Kryvyy Rih', 'Ukraine'),
 ('Lvov', 'Ukraine'),
 ('Makiyivka', 'Ukraine'),
 ('Mazyr', 'Belarus'),
 ('Minsk', 'Belarus'),
 ('Nis', 'Serbia'),
 ('Novi Sad', 'Serbia'),
 ('Orsha', 'Belarus'),
 ('Oslo', 'Norway'),
 ('Pinsk', 'Belarus'),
 ('Podgorica', 'Montenegro'),
 ('Rivne', 'Ukraine'),
 ('Sarajevo', 'Bosnia and Herzegovina'),
 ('Skopje', 'Macedonia'),
 ('Stavanger', 'Norway'),
 ('Sumy', 'Ukraine'),
 ('Trondheim', 'Norway'),
 ('Yevpatoriya', 'Ukraine'),
 ('Zhytomyr', 'Ukraine'),
 ('Zurich', 'Switzerland')]

*Add your city*

In [42]:
%%sql
insert into NonEU values ('my-city','my-country');
select * from NonEU

 * sqlite://
1 rows affected.
Done.

[('Andorra', 'Andorra'),
 ('Balti', 'Moldova'),
 ('Basel', 'Switzerland'),
 ('Belgrade', 'Serbia'),
 ('Bergen', 'Norway'),
 ('Bila Tserkva', 'Ukraine'),
 ('Bodo', 'Norway'),
 ('Brest', 'Belarus'),
 ('Cherkasy', 'Ukraine'),
 ('Chernihiv', 'Ukraine'),
 ('Chernivtsi', 'Ukraine'),
 ('Chisinau', 'Moldova'),
 ('Elbasan', 'Albania'),
 ('Geneva', 'Switzerland'),
 ('Horlivka', 'Ukraine'),
 ('Hrodna', 'Belarus'),
 ('Kherson', 'Ukraine'),
 ('Kiev', 'Ukraine'),
 ('Kremenchuk', 'Ukraine'),
 ('Kryvyy Rih', 'Ukraine'),
 ('Lvov', 'Ukraine'),
 ('Makiyivka', 'Ukraine'),
 ('Mazyr', 'Belarus'),
 ('Minsk', 'Belarus'),
 ('Nis', 'Serbia'),
 ('Novi Sad', 'Serbia'),
 ('Orsha', 'Belarus'),
 ('Oslo', 'Norway'),
 ('Pinsk', 'Belarus'),
 ('Podgorica', 'Montenegro'),
 ('Rivne', 'Ukraine'),
 ('Sarajevo', 'Bosnia and Herzegovina'),
 ('Skopje', 'Macedonia'),
 ('Stavanger', 'Norway'),
 ('Sumy', 'Ukraine'),
 ('Trondheim', 'Norway'),
 ('Yevpatoriya', 'Ukraine'),
 ('Zhytomyr', 'Ukraine'),
 ('Zurich', 'Switzerland'),
 ('my-city', 'my-country')]

### <font color = 'green'>**Your Turn - Advanced SQL on World Cup Data**</font>

In [43]:
# Create database tables from CSV files
with open('Players.csv') as f: Players = pd.read_csv(f, index_col=0)
%sql drop table if exists Players;
%sql --persist Players
with open('Teams.csv') as f: Teams = pd.read_csv(f, index_col=0)
%sql drop table if exists Teams;
%sql --persist Teams

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.
 * sqlite://

'Persisted teams'

#### Look at sample of Players and Teams tables

In [44]:
%%sql
select * from Players limit 5

 * sqlite://
Done.

[('Abdoun', 'Algeria', 'midfielder', 16, 0, 6, 0, 0),
 ('Belhadj', 'Algeria', 'defender', 270, 1, 146, 8, 0),
 ('Boudebouz', 'Algeria', 'midfielder', 74, 3, 28, 1, 0),
 ('Bougherra', 'Algeria', 'defender', 270, 1, 89, 11, 0),
 ('Chaouchi', 'Algeria', 'goalkeeper', 90, 0, 17, 0, 2)]

In [45]:
%%sql
select * from Teams limit 5

 * sqlite://
Done.

[('Brazil', 1, 5, 3, 1, 1, 9, 4, 7, 2),
 ('Spain', 2, 6, 5, 0, 1, 7, 2, 3, 0),
 ('Portugal', 3, 4, 1, 2, 1, 7, 1, 8, 1),
 ('Netherlands', 4, 6, 6, 0, 0, 12, 5, 15, 0),
 ('Italy', 5, 3, 0, 2, 1, 4, 5, 5, 0)]

*1) Find all pairs of teams who have the same number of goalsFor as
each other and the same number of goalsAgainst as each other.
Return the teams and numbers of goalsFor and goalsAgainst.
Make sure to return each pair only once.*

In [46]:
%%sql
select T1.team, T1.goalsFor, T2.team, T2.goalsFor
from Teams T1, Teams T2
where T1.goalsFor = T2.goalsFor
and T1.goalsAgainst = T2.goalsAgainst

 * sqlite://
Done.

[('Brazil', 9, 'Brazil', 9),
 ('Spain', 7, 'Spain', 7),
 ('Portugal', 7, 'Portugal', 7),
 ('Netherlands', 12, 'Netherlands', 12),
 ('Italy', 4, 'Italy', 4),
 ('Italy', 4, 'Mexico', 4),
 ('Germany', 13, 'Germany', 13),
 ('Argentina', 10, 'Argentina', 10),
 ('England', 3, 'Chile', 3),
 ('England', 3, 'England', 3),
 ('England', 3, 'Nigeria', 3),
 ('England', 3, 'South Africa', 3),
 ('France', 1, 'France', 1),
 ('Greece', 2, 'Cameroon', 2),
 ('Greece', 2, 'Greece', 2),
 ('USA', 5, 'USA', 5),
 ('Serbia', 2, 'Serbia', 2),
 ('Uruguay', 9, 'Uruguay', 9),
 ('Mexico', 4, 'Italy', 4),
 ('Mexico', 4, 'Mexico', 4),
 ('Chile', 3, 'Chile', 3),
 ('Chile', 3, 'England', 3),
 ('Chile', 3, 'Nigeria', 3),
 ('Chile', 3, 'South Africa', 3),
 ('Cameroon', 2, 'Cameroon', 2),
 ('Cameroon', 2, 'Greece', 2),
 ('Australia', 3, 'Australia', 3),
 ('Australia', 3, 'Denmark', 3),
 ('Nigeria', 3, 'Chile', 3),
 ('Nigeria', 3, 'England', 3),
 ('Nigeria', 3, 'Nigeria', 3),
 ('Nigeria', 3, 'South Africa', 3),
 ('Switzerland', 1, 'Switzerland', 1),
 ('Slovenia', 3, 'Slovenia', 3),
 ('Ivory Coast', 4, 'Ivory Coast', 4),
 ('Algeria', 0, 'Algeria', 0),
 ('Paraguay', 3, 'Paraguay', 3),
 ('Ghana', 5, 'Ghana', 5),
 ('Slovakia', 5, 'Slovakia', 5),
 ('Denmark', 3, 'Australia', 3),
 ('Denmark', 3, 'Denmark', 3),
 ('Honduras', 0, 'Honduras', 0),
 ('Japan', 4, 'Japan', 4),
 ('South Korea', 6, 'South Korea', 6),
 ('New Zealand', 2, 'New Zealand', 2),
 ('South Africa', 3, 'Chile', 3),
 ('South Africa', 3, 'England', 3),
 ('South Africa', 3, 'Nigeria', 3),
 ('South Africa', 3, 'South Africa', 3),
 ('North Korea', 1, 'North Korea', 1)]

*2) Find all teams with ranking <30 where no player made more than 150 passes. Return the team and ranking.*

In [47]:
%%sql
select T.team, T.ranking
from Teams T
where T.ranking < 30
and not exists (select * from Players P
                where P.team = T.team
                and P.passes > 150)

 * sqlite://
Done.

[('France', 9), ('Nigeria', 21), ('Switzerland', 24)]

*3) Which players made more shots than 5x the overall average number of shots? Return the player surname, position, and team.*

In [48]:
%%sql
select P.surname, P.position, P.team
from Players P
where P.shots > 5 * (select avg(shots) from Players)

 * sqlite://
Done.

[('Higuain', 'forward', 'Argentina'),
 ('Messi', 'forward', 'Argentina'),
 ('Podolski', 'forward', 'Germany'),
 ('Boateng', 'midfielder', 'Ghana'),
 ('Gyan', 'forward', 'Ghana'),
 ('Sneijder', 'midfielder', 'Netherlands'),
 ('van Persie', 'forward', 'Netherlands'),
 ('Jong Tae-Se', 'forward', 'North Korea'),
 ('Ronaldo', 'forward', 'Portugal'),
 ('Park Chu-Young', 'forward', 'South Korea'),
 ('Villa', 'forward', 'Spain'),
 ('Forlan', 'forward', 'Uruguay'),
 ('Suarez', 'forward', 'Uruguay'),
 ('Dempsey', 'midfielder', 'USA')]

*4) Find all team-position pairs where the average number of passes made by players in that position on that team is greater than 150. Return the team-position pairs.*

In [49]:
%%sql
SELECT T.team, P.position
FROM Teams T, Players P
WHERE T.team = P.team
GROUP BY T.team, P.position
HAVING avg(P.passes) > 150

 * sqlite://
Done.

[('Argentina', 'midfielder'),
 ('Brazil', 'defender'),
 ('Germany', 'defender'),
 ('Germany', 'midfielder'),
 ('Ghana', 'midfielder'),
 ('Mexico', 'defender'),
 ('Netherlands', 'defender'),
 ('Netherlands', 'midfielder'),
 ('Spain', 'defender'),
 ('Spain', 'midfielder')]

*5) Find all teams whose defenders averaged more than 150 passes. Return the team and average number of passes by defenders, in descending order of average passes.*

In [50]:
%%sql
select T.team, avg(P.passes)
from Teams T, Players P
where T.team = P.team
and P.position = 'defender'
group by T.team
having avg(P.passes) > 150
order by avg(P.passes)

 * sqlite://
Done.

[('Mexico', 152.14285714285714),
 ('Netherlands', 182.5),
 ('Germany', 189.83333333333334),
 ('Brazil', 190.0),
 ('Spain', 213.0)]

### <font color = 'green'>**Your Turn Extra - Advanced SQL on Titanic Data**</font>

<font color="red">File access required:</font> In Colab these extra problems require first uploading **Titanic.csv** using the *Files* feature in the left toolbar. If running the notebook on a local computer, simply ensure this file is in the same workspace as the notebook.

In [51]:
# Load dataabase table from CSV file
with open('Titanic.csv') as f: Titanic = pd.read_csv(f, index_col=0)
%sql drop table if exists Titanic;
%sql --persist Titanic

 * sqlite://
Done.
 * sqlite://

'Persisted titanic'

#### Look at sample of Titanic table

In [52]:
%%sql
select * from Titanic limit 5

 * sqlite://
Done.

[('Abbing', 'Mr. Anthony', 'M', 42.0, 3, 7.55, 'Southampton', 'no'),
 ('Abbott', 'Mrs. Stanton (Rosa Hunt)', 'F', 35.0, 3, 20.25, 'Southampton', 'yes'),
 ('Abbott', 'Mr. Rossmore Edward', 'M', 16.0, 3, 20.25, 'Southampton', 'no'),
 ('Abelson', 'Mr. Samuel', 'M', 30.0, 2, 24.0, 'Cherbourg', 'no'),
 ('Abelson', 'Mrs. Samuel (Hannah Wizosky)', 'F', 28.0, 2, 24.0, 'Cherbourg', 'yes')]

*1) Find pairs of passengers who are likely to be twin children: same last name, same age, same embarkation, and age is under 18. Return each pair once, including their last name, first names, age, and embarkation city.*

In [53]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*2) Which embarkation cities have more than 40 passengers whose age is missing? Reminder: Blanks in SQL tables are given a special value called 'null', and conditions 'A is null' and 'A is not null' can be used in Where clauses to check whether attribute A has the 'null' value.*

In [54]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*3) Find all classes where the average fare paid by passengers in that class was more than twice the overall average or less than half the overall average.*

In [55]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*4) What is the average number of passengers per last name? Hint: Requires using a subquery in the From clause*

In [56]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*5) List each class and its survival rate, i.e., the fraction of passengers in that class who survived. Hints: Use subqueries in the From clause to compute the number of survivers per class and total passengers per class, and force floating point division by multiplying one operand by 1.0*

In [57]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*6) Modify your previous query to return the survival rate by gender, i.e., of females and of males.*

In [58]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*7) Now return the survival rate of children versus adults, i.e., of passengers under age 18 versus those 18 or over (ignoring passengers whose age is missing).*

In [59]:
%%sql
YOUR QUERY HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

### <font color = 'green'>**Your Turn Extra - SQL Data Modification on Titanic Data**</font>

In [60]:
# Reload table from CSV file
# NOTE: You may want to reload frequently to reset the data as you
# experiment with modifications
with open('Titanic.csv') as f: Titanic = pd.read_csv(f, index_col=0)
%sql drop table if exists Titanic;
%sql persist Titanic

 * sqlite://
Done.
 * sqlite://
(sqlite3.OperationalError) near "persist": syntax error
[SQL: persist Titanic]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*1) Subtract 5 from the fare paid by any passenger under the age of 10. Then compute the new average fare. NOTE: You can put multiple SQL statements in one cell separated by a semicolon.*

In [61]:
%%sql
YOUR CODE HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR CODE HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*2) Create a new table called Survivors, containing the last and first names of all passengers who survived. Then count the number of tuples in the new table.*

In [62]:
%%sql
YOUR CODE HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR CODE HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*3) In the Titanic table delete all but the highest-paying passengers.*

In [63]:
%%sql
YOUR CODE HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR CODE HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

*4) In what's left of the table after (3), insert a new tuple for yourself. You can decide your class, fare, where you embarked, and whether you survived. Then show the whole table.*

In [64]:
%%sql
YOUR CODE HERE

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR CODE HERE]
(Background on this error at: https://sqlalche.me/e/20/e3q8)